# Generated by Django 5.1.7 on 2025-04-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('transfer', 'Transfer')], max_length=10)),
                ('service_type', models.CharField(choices=[('solo', 'Solo'), ('contract', 'Contract')], max_length=10)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('staff_role', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('staff_name', models.ForeignKey(blank=True, limit_choices_to={'is_not_secretary': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Rendered',
                'verbose_name_plural': 'Services Rendered',
                'ordering': ['-service_date'],
            },
        ),
    ]
