# Generated by Django 5.1.7 on 2025-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_servicerendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerendered',
            name='service_rendered',
            field=models.CharField(blank=True, choices=[('Massage Therapy', 'Massage Therapy'), ('Facial Treatments', 'Facial Treatments'), ('Aromatherapy', 'Aromatherapy'), ('Body Scrubs', 'Body Scrubs'), ('Steam & Sauna', 'Steam & Sauna'), ('Nail Care', 'Nail Care')], max_length=20, null=True),
        ),
    ]
